kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: webinar-user-access
  namespace: webinar
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: webinar-user-full-access
subjects:
- kind: Group
  namespace: webinar
  name: "change me"