kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: tenant1-ns-admin-rolebinding
  namespace: tenant1
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: tenant1-ns-admin-role
subjects:
- kind: Group
  namespace: tenant1
  name: #PLCAEHOLDER FOR THE TENANT1 NAMESPACE ADMIN GROUP ID